version: 2.1
orbs:
  docker: circleci/docker@1.0.0
  heroku: circleci/heroku@1.2.2
workflows:
  docker_deploy:
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only: master # only run deploy-via-git job on master branch

